apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: istio-sidecars
  namespace: observability
  labels:
    app: istio-sidecars
spec:
  namespaceSelector:
    matchNames:
    - super-fortnight
  selector:
    matchExpressions:
    - key: service.istio.io/canonical-name
      operator: Exists
  podMetricsEndpoints:
  - port: http-envoy-prom
    interval: 30s
    path: /stats/prometheus
