apiVersion: v1
kind: Service
metadata:
  name: kiali
  namespace: observability
  labels:
    app: kiali
spec:
  type: ClusterIP
  ports:
  - port: 20001
    targetPort: 20001
    name: http
  selector:
    app: kiali
