# This automatically injects all the ConfigMap values as environment variables into the aggregator pods.
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-config
  namespace: microservices
  labels:
    app: microservices
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  ROCK_SERVICE_URL: "http://rock-service:3001"
  PAPER_SERVICE_URL: "http://paper-service:3002"
  SCISSOR_SERVICE_URL: "http://scissor-service:3003"
  LOG_LEVEL: "info"
  NODE_ENV: "production"
