apiVersion: v1
kind: Namespace
metadata:
  name: super-fortnight
  labels:
    name: "super-fortnight-microservices"
    environment: development
    istio-injection: enabled
  annotations:
    argocd.argoproj.io/sync-wave: "0"
