apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: prometheus
  namespace: observability
spec:
  hosts:
    - prometheus.example.com
  gateways:
    - istio-system/observability-gateway
  http:
    - route:
        - destination:
            host: prometheus-server.observability.svc.cluster.local
            port:
              number: 80
