apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-ingress-gateway
  namespace: argocd
  labels:
    team: platform
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/ashutosh-18k92/platform-gitops.git
    targetRevision: HEAD
    path: infrastructure/envoy/gateways
  destination:
    server: https://kubernetes.default.svc
    namespace: microservices
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
