apiVersion: integreatly.org/v1alpha1
kind: GrafanaDatasource
metadata:
  name: jaeger
  namespace: observability
spec:
  datasource:
    type: jaeger
    url: http://tracing-query.observability:16686
    access: proxy
    isDefault: true

