apiVersion: v1
kind: ConfigMap
metadata:
  name: service-config
  namespace: microservices
data:
  ROCK_SERVICE_URL: "http://rock-service:3001"
  PAPER_SERVICE_URL: "http://paper-service:3002"
  SCISSOR_SERVICE_URL: "http://scissor-service:3003"
  LOG_LEVEL: "info"
